import { Account } from "@/utils/types";

export const mockAccounts: Account[] = [
  {
    account_id: "ACC001",
    holder: {
      firstName: "Andrew",
      lastName: "McNulty",
      phoneNumber: "+1-224-463-7589",
      nickName: "jford",
      gender: "Male",
      email: "a*@gmail.com",
      jointNames: "",
      username: "sample1",
      password: "sample1",
    },
    bank_details: {
      account_type: "Checking",
      balance_usd: 115678.0,
    },
    transaction_mgs_code: {
      transaction_text_msg:
        "To continue this transaction, Please enter the code sent to you",
      transaction_code: "",
      wireDate: true,
    },
    transaction_history: [
      {
        transaction_id: "TXN001",
        dateTime: "June 10 2024, 3:32:32 am",
        description: "Grimms supply holding's",
        status: "Success",
        amount_usd: 58000.0,
        account_no: "****5009",
      },
      {
        transaction_id: "TXN002",
        dateTime: "April 15 2023, 1:04:02 pm",
        description: "Transfer from TABITHA MARTEL",
        status: "Success",
        amount_usd: 250000.0,
        account_no: "****2930",
      },
      {
        transaction_id: "TXN003",
        dateTime: "February 8 2022, 10:11:22 am",
        description: "Transfer from NICHOLAS DUKE",
        status: "Success",
        amount_usd: 650000.0,
        account_no: "****3839",
      },
      {
        transaction_id: "TXN004",
        dateTime: "July 2 2021, 7:08:32 am",
        description: "Transfer from BRANDON PERKINS",
        status: "Success",
        amount_usd: 175000.0,
        account_no: "****3249",
      },
      {
        transaction_id: "TXN005",
        dateTime: "November 23 2020, 1:15:02 pm",
        description: "Sinlair's Store - Trx",
        status: "Success",
        amount_usd: -650.0,
        account_no: "****1403",
      },
      {
        transaction_id: "TXN006",
        dateTime: "April 23 2020, 8:15:02 pm",
        description: "Project Milestone Payment",
        status: "Success",
        amount_usd: 65000.0,
        account_no: "****1403",
      },
      {
        transaction_id: "TXN007",
        dateTime: "March 15, 2019, 7:20:15 am",
        description: "Project Completion Bonus",
        status: "Success",
        amount_usd: 18000.0,
        account_no: "****5012",
      },
      {
        transaction_id: "TXN008",
        dateTime: "February 12, 2019, 10:45:00 am",
        description: "Walmart",
        status: "Success",
        amount_usd: -4000.0,
        account_no: "****5013",
      },
      {
        transaction_id: "TXN009",
        dateTime: "April 16, 2019, 2:45:15 pm",
        description: "AT&T",
        status: "Success",
        amount_usd: -400.0,
        account_no: "****5007",
      },
      {
        transaction_id: "TXN010",
        dateTime: "April 23 2020, 8:15:02 pm",
        description: "Project Milestone Payment",
        status: "Success",
        amount_usd: 65000.0,
        account_no: "****1403",
      },
      {
        transaction_id: "TXN011",
        dateTime: "March 15, 2019, 7:20:15 am",
        description: "Project Completion Bonus",
        status: "Success",
        amount_usd: 18000.0,
        account_no: "****5012",
      },
      {
        transaction_id: "TXN012",
        dateTime: "February 12, 2019, 10:45:00 am",
        description: "Walmart",
        status: "Success",
        amount_usd: -4000.0,
        account_no: "****5013",
      },
      {
        transaction_id: "TXN013",
        dateTime: "April 16, 2019, 2:45:15 pm",
        description: "AT&T",
        status: "Success",
        amount_usd: -400.0,
        account_no: "****5007",
      },
      {
        transaction_id: "TXN014",
        dateTime: "April 23 2020, 8:15:02 pm",
        description: "Project Milestone Payment",
        status: "Success",
        amount_usd: 65000.0,
        account_no: "****1403",
      },
      {
        transaction_id: "TXN015",
        dateTime: "March 15, 2019, 7:20:15 am",
        description: "Project Completion Bonus",
        status: "Success",
        amount_usd: 18000.0,
        account_no: "****5012",
      },
      {
        transaction_id: "TXN016",
        dateTime: "February 12, 2019, 10:45:00 am",
        description: "Walmart",
        status: "Success",
        amount_usd: -4000.0,
        account_no: "****5013",
      },
      {
        transaction_id: "TXN017",
        dateTime: "April 16, 2019, 2:45:15 pm",
        description: "AT&T",
        status: "Success",
        amount_usd: -400.0,
        account_no: "****5007",
      },
    ],
  },
  {
    account_id: "ACC002",
    holder: {
      firstName: "Dr James Allen, Jr (DDS dentistry",
      lastName: "",
      nickName: "Dr.",
      email: "d*@gmail.com",
      jointNames: "",
      username: "HensonA101",
      password: "Lawcleg112",
    },
    bank_details: {
      account_type: "Checking",
      balance_usd: 150000.0,
    },
    transaction_mgs_code: {
      transaction_text_msg:
        "To continue this transaction, Please enter the code sent to you",
      transaction_code: "",
      wireDate: true,
    },
    transaction_history: [
      {
        transaction_id: "TXN001",
        dateTime: "July 17 2024, 8:03:06 am",
        description: "Transfer from J. David Thompson Estate",
        status: "Success",
        amount_usd: 150000.0,
        account_no: "****5009",
      },
    ],
  },
  {
    account_id: "ACC003",
    account_type: "current",
    holder: {
      firstName: "Maria Peoples",
      lastName: "",
      nickName: "",
      email: "m*@gmail.com",
      jointNames: "",
      username: "Bryant01",
      password: "Onelove",
    },
    bank_details: {
      account_type: "Checking",
      balance_usd: 35000.0,
      saving_balance_usd: 25000.0,
    },
    transaction_mgs_code: {
      transaction_text_msg:
        "To continue this transaction, Please enter the code sent to you",
      transaction_code: "",
      wireDate: true,
    },
    transaction_history: [
      {
        transaction_id: "TXN001",
        dateTime: "July 31 2024, 12:03:06 pm",
        description: "Deposit from Kelvin Mills",
        status: "Pending",
        amount_usd: 25000.0,
        account_no: "****5009",
      },
    ],
  },
  {
    account_id: "ACC004",
    account_type: "",
    holder: {
      firstName: "David Bill Morales",
      lastName: "",
      phoneNumber: "281-497-9969",
      email: "david.morales45@hotmail.com",
      jointNames: "",
      username: "DavidM9",
      password: "Davidandpaulee2",
    },
    bank_details: {
      account_type: "Checking",
      balance_usd: 2850000.0,
    },
    transaction_mgs_code: {
      transaction_text_msg:
        "To continue this transaction, please enter the code sent to you",
      transaction_code: "2378322762",
      lastStepText:
        "Your account is on hold. You cannot make transactions right now. Please contact our customer service team for assistance.",
      wireDate: true,
    },
    transaction_history: [
      {
        transaction_id: "TXN001",
        dateTime: "August 10 2021",
        description: "Transfer from Dollar General",
        status: "Success",
        amount_usd: -2000.0,
        account_no: "****5009",
      },
      {
        transaction_id: "TXN002",
        dateTime: "June 15 2021",
        description: "Transfer from CVS Pharmacy",
        status: "Success",
        amount_usd: -4000.0,
        account_no: "****2930",
      },
      {
        transaction_id: "TXN003",
        dateTime: "February 8 2021",
        description: "Transfer from Ace Cash Express",
        status: "Success",
        amount_usd: -6350.0,
        account_no: "****3839",
      },
      {
        transaction_id: "TXN004",
        dateTime: "January 25 2021",
        description: "Transfer from Ross Stores",
        status: "Success",
        amount_usd: -5500.0,
        account_no: "****3249",
      },
      {
        transaction_id: "TXN005",
        dateTime: "January 20 2021",
        description: "Amazon Fresh",
        status: "Success",
        amount_usd: -350.0,
        account_no: "****3839",
      },
      {
        transaction_id: "TXN006",
        dateTime: "September 23 2020",
        description: "7 Eleven",
        status: "Success",
        amount_usd: -650.0,
        account_no: "****1403",
      },
      {
        transaction_id: "TXN007",
        dateTime: "April 23 2020",
        description: "Mortgage Interest",
        status: "Success",
        amount_usd: 40000.0,
        account_no: "****1403",
      },
      {
        transaction_id: "TXN008",
        dateTime: "April 21 2020",
        description: "Walmart",
        status: "Success",
        amount_usd: -200.0,
        account_no: "****1403",
      },
      {
        transaction_id: "TXN009",
        dateTime: "March 15, 2020",
        description: "Wire Transfer Payment",
        status: "Success",
        amount_usd: 40000.0,
        account_no: "****5012",
      },
      {
        transaction_id: "TXN010",
        dateTime: "March 10, 2020",
        description: "Walmart",
        status: "Success",
        amount_usd: -450.0,
        account_no: "****5012",
      },
      {
        transaction_id: "TXN011",
        dateTime: "March 5, 2020",
        description: "Walmart",
        status: "Success",
        amount_usd: -300.0,
        account_no: "****5012",
      },
      {
        transaction_id: "TXN012",
        dateTime: "February 20, 2020",
        description: "Bill Payment",
        status: "Success",
        amount_usd: -3000.0,
        account_no: "****5013",
      },
      {
        transaction_id: "TXN013",
        dateTime: "February 17, 2020",
        description: "Walmart",
        status: "Success",
        amount_usd: -500.0,
        account_no: "****5007",
      },
      {
        transaction_id: "TXN014",
        dateTime: "February 16, 2022",
        description: "Walmart",
        status: "Success",
        amount_usd: -100.0,
        account_no: "****1403",
      },
      {
        transaction_id: "TXN015",
        dateTime: "February 15, 2020",
        description: "Walmart",
        status: "Success",
        amount_usd: -750.0,
        account_no: "****5012",
      },
      {
        transaction_id: "TXN016",
        dateTime: "February 12, 2020",
        description: "Walmart",
        status: "Success",
        amount_usd: -350.0,
        account_no: "****5013",
      },
      {
        transaction_id: "TXN017",
        dateTime: "October 12, 2019",
        description: "Walmart",
        status: "Success",
        amount_usd: -120.0,
        account_no: "****5007",
      },
      {
        transaction_id: "TXN018",
        dateTime: "September 23, 2019",
        description: "Verizon",
        status: "Success",
        amount_usd: -410.0,
        account_no: "****5007",
      },
      {
        transaction_id: "TXN019",
        dateTime: "September 8 2019",
        description: "Zelle Transfer #c1cvsjsjsk",
        status: "Success",
        amount_usd: 2000.0,
        account_no: "****1403",
      },
      {
        transaction_id: "TXN020",
        dateTime: "August 25, 2019",
        description: "Zelle transfer #c5ceweskw",
        status: "Success",
        amount_usd: 1900.0,
        account_no: "****5012",
      },
      {
        transaction_id: "TXN021",
        dateTime: "August 12, 2019",
        description: "Walmart",
        status: "Success",
        amount_usd: -1050.0,
        account_no: "****5013",
      },
      {
        transaction_id: "TXN02122",
        dateTime: "August 5, 2019",
        description: "Credit from Zendesk",
        status: "Success",
        amount_usd: 350000.0,
        account_no: "****5013",
      },
      {
        transaction_id: "TXN022",
        dateTime: "July 20, 2019",
        description: "Chase Credit Card Bill",
        status: "Success",
        amount_usd: -1900.0,
        account_no: "****5007",
      },
      {
        transaction_id: "TXN023",
        dateTime: "July 18, 2019",
        description: "Walmart",
        status: "Success",
        amount_usd: -1100.0,
        account_no: "****5007",
      },
      {
        transaction_id: "TXN024",
        dateTime: "June 16, 2019",
        description: "AT&T",
        status: "Success",
        amount_usd: -400.0,
        account_no: "****5007",
      },
      {
        transaction_id: "TXN025",
        dateTime: "June 4, 2019",
        description: "Walmart",
        status: "Success",
        amount_usd: -1100.0,
        account_no: "****5007",
      },
      {
        transaction_id: "TXN018343",
        dateTime: "April 6, 2019",
        description: "Transfer from David bill external Account",
        status: "Success",
        amount_usd: 1500000.0,
        account_no: "****5007",
      },
      {
        transaction_id: "TXN018343",
        dateTime: "April 4, 2019",
        description: "Transfer from David bill external Account",
        status: "Success",
        amount_usd: 1000000.0,
        account_no: "****5007",
      },
      {
        transaction_id: "TXN01934343",
        dateTime: "March 4, 2019",
        description: "Account Open",
        status: "Success",
        amount_usd: 100.0,
        account_no: "****5007",
      },
    ],
  },
  {
    account_id: "ACC005",
    account_type: "",
    holder: {
      firstName: "Lester",
      lastName: "Dorr",
      phoneNumber: "+1-***-***-****",
      email: "",
      jointNames: "",
      username: "Lestermarie101",
      password: "Dorr101@$",
    },
    bank_details: {
      account_type: "Checking",
      balance_usd: 1610000.0,
    },
    transaction_mgs_code: {
      transaction_text_msg:
        "To continue this transaction, please enter the code sent to you",
      transaction_code: "2378322762",
      lastStepText:
        "Your account is on hold. You cannot make transactions right now. Please contact our customer service team for assistance.",
      wireDate: true,
    },
    transaction_history: [
      {
        transaction_id: "TXN005",
        dateTime: "October 21, 2024",
        description: "Wire transfer from Empower Bank",
        status: "Success",
        amount_usd: 420000.0,
        account_no: "****5009",
      },
      {
        transaction_id: "TXN004",
        dateTime: "October 20, 2024",
        description: "Wire transfer from Empower Bank",
        status: "Success",
        amount_usd: 450000.0,
        account_no: "****5009",
      },
      {
        transaction_id: "TXN003",
        dateTime: "October 19, 2024",
        description: "Wire transfer from Empower Bank",
        status: "Success",
        amount_usd: 360000.0,
        account_no: "****5009",
      },
      {
        transaction_id: "TXN002",
        dateTime: "October 18, 2024",
        description: "Wire transfer from Empower Bank",
        status: "Success",
        amount_usd: 380000.0,
        account_no: "****5009",
      },
      // {
      //   transaction_id: "TXN001",
      //   dateTime: "October 4, 2024",
      //   description: "Wire transfer from Empower Bank",
      //   status: "Success",
      //   amount_usd: 320000.0,
      //   account_no: "****5009",
      // },
      {
        transaction_id: "TXN001",
        dateTime: "September 20 2015",
        description: "Transfer to Charity Home Ca.",
        status: "Success",
        amount_usd: -280000.0,
        account_no: "****5009",
      },
      {
        transaction_id: "TXN002",
        dateTime: "August 15 2015",
        description: "Celeb City Farms ",
        status: "Success",
        amount_usd: 400000.0,
        account_no: "****5009",
      },
      {
        transaction_id: "TXN003",
        dateTime: "May 10 2014",
        description: "Company Officials",
        status: "Success",
        amount_usd: -150750.0,
        account_no: "****2930",
      },
      {
        transaction_id: "TXN003",
        dateTime: "January 5 2014",
        description: "Transfer from Tee~Energy services",
        status: "Success",
        amount_usd: 850000.0,
        account_no: "****2930",
      },
      {
        transaction_id: "TXN004",
        dateTime: "October 19 2013",
        description: "Company Van Maintenance",
        status: "Success",
        amount_usd: -350.0,
        account_no: "****2930",
      },
      {
        transaction_id: "TXN005",
        dateTime: "September 13 2013",
        description: "Transfer from Nikky&co enterprises",
        status: "Success",
        amount_usd: 475000.0,
        account_no: "****3839",
      },
      {
        transaction_id: "TXN006",
        dateTime: "June 24 2012",
        description: "Appointment Form Payment",
        status: "Success",
        amount_usd: 650.0,
        account_no: "****3249",
      },
      {
        transaction_id: "TXN007",
        dateTime: "February 3 2012",
        description: "Department Workers",
        status: "Success",
        amount_usd: -105400.0,
        account_no: "****1403",
      },
      {
        transaction_id: "TXN008",
        dateTime: "December 8 2011",
        description: "Transfer from Chad Estate Management",
        status: "Success",
        amount_usd: 750000.0,
        account_no: "****1403",
      },
      {
        transaction_id: "TXN009",
        dateTime: "May 20 2010",
        description: "Bammy Work Wear and Maintenance",
        status: "Success",
        amount_usd: -4500.0,
        account_no: "****5012",
      },
      {
        transaction_id: "TXN010",
        dateTime: "March 23 2020",
        description: "Transfer from JayJay Group",
        status: "Success",
        amount_usd: 12000.0,
        account_no: "****5013",
      },
    ],
  },
  {
    account_id: "ACC006",
    account_type: "",
    holder: {
      firstName: "Gordon",
      lastName: "Roberts",
      phoneNumber: "+1-***-***-****",
      email: "g@gmail.com",
      jointNames: "",
      username: "Gordon123$",
      password: "Ilovenick4ever!",
    },
    bank_details: {
      account_type: "Checking",
      account_type2: "saving_account",
      balance_usd: 607465.55,
      saving_balance_usd: 300000.0,
    },
    transaction_mgs_code: {
      transaction_text_msg:
        "To continue this transaction, please enter the code sent to you",
      transaction_code: "2378322762",
      lastStepText:
        "Your account is on hold. You cannot make transactions right now. Please contact our customer service team for assistance.",
      wireDate: true,
    },
    transaction_history: [
      {
        transaction_id: "TXN001",
        dateTime: "October 10, 2024",
        description: "Grant from Federal Research Fund",
        status: "Success",
        amount_usd: 75000.0,
        account_no: "****5009",
      },
      {
        transaction_id: "TXN002",
        dateTime: "September 28, 2024",
        description: "Debit - Purchase at SuperMart",
        status: "Success",
        amount_usd: -230.55,
        account_no: "****5009",
      },
      {
        transaction_id: "TXN003",
        dateTime: "September 15, 2024",
        description: "Grant from Science Innovation Fund",
        status: "Success",
        amount_usd: 50000.0,
        account_no: "****5009",
      },
      {
        transaction_id: "TXN004",
        dateTime: "August 30, 2024",
        description: "Debit - Purchase at TechStore",
        status: "Success",
        amount_usd: -785.99,
        account_no: "****5009",
      },
      {
        transaction_id: "TXN005",
        dateTime: "August 19, 2024",
        description: "Grant from Education Support Fund",
        status: "Success",
        amount_usd: 65000.0,
        account_no: "****5009",
      },
      {
        transaction_id: "TXN006",
        dateTime: "August 7, 2024",
        description: "Debit - Purchase at Fresh Foods Groceries",
        status: "Success",
        amount_usd: -140.75,
        account_no: "****5009",
      },
      {
        transaction_id: "TXN007",
        dateTime: "July 22, 2024",
        description: "Grant from Nonprofit Startup Initiative",
        status: "Success",
        amount_usd: 83000.0,
        account_no: "****5009",
      },
      {
        transaction_id: "TXN008",
        dateTime: "July 5, 2024",
        description: "Debit - Purchase at Electronics Central",
        status: "Success",
        amount_usd: -980.12,
        account_no: "****5009",
      },
      {
        transaction_id: "TXN009",
        dateTime: "June 28, 2024",
        description: "Grant from Tech Development Foundation",
        status: "Success",
        amount_usd: 92000.0,
        account_no: "****5009",
      },
      {
        transaction_id: "TXN010",
        dateTime: "June 10, 2024",
        description: "Grant from Small Business Initiative",
        status: "Success",
        amount_usd: 60000.0,
        account_no: "****5009",
      },
      {
        transaction_id: "TXN011",
        dateTime: "May 25, 2024",
        description: "Debit - Purchase at Best Buy",
        status: "Success",
        amount_usd: -432.88,
        account_no: "****5009",
      },
      {
        transaction_id: "TXN012",
        dateTime: "May 7, 2024",
        description: "Grant from Community Development Fund",
        status: "Success",
        amount_usd: 48000.0,
        account_no: "****5009",
      },
      {
        transaction_id: "TXN013",
        dateTime: "April 30, 2024",
        description: "Grant from Empower Youth Foundation",
        status: "Success",
        amount_usd: 72000.0,
        account_no: "****5009",
      },
      {
        transaction_id: "TXN014",
        dateTime: "April 14, 2024",
        description: "Debit - Purchase at Walmart",
        status: "Success",
        amount_usd: -259.99,
        account_no: "****5009",
      },
      {
        transaction_id: "TXN015",
        dateTime: "March 28, 2024",
        description: "Grant from Local Business Growth Fund",
        status: "Success",
        amount_usd: 56000.0,
        account_no: "****5009",
      },
      {
        transaction_id: "TXN016",
        dateTime: "March 11, 2024",
        description: "Debit - Purchase at Target",
        status: "Success",
        amount_usd: -172.45,
        account_no: "****5009",
      },
      {
        transaction_id: "TXN017",
        dateTime: "February 25, 2024",
        description: "Grant from Innovation and Entrepreneurship Fund",
        status: "Success",
        amount_usd: 97000.0,
        account_no: "****5009",
      },
      {
        transaction_id: "TXN018",
        dateTime: "February 3, 2024",
        description: "Grant from Global Sustainability Program",
        status: "Success",
        amount_usd: 86000.0,
        account_no: "****5009",
      },
      {
        transaction_id: "TXN019",
        dateTime: "January 15, 2024",
        description: "Debit - Purchase at Clothing Outlet",
        status: "Success",
        amount_usd: -320.6,
        account_no: "****5009",
      },
      {
        transaction_id: "TXN020",
        dateTime: "December 1, 2023",
        description: "Grant from Research for Education Initiative",
        status: "Success",
        amount_usd: 67000.0,
        account_no: "****5009",
      },
      {
        transaction_id: "TXN021",
        dateTime: "November 28, 2023",
        description: "Grant from Research for Education Initiative",
        status: "Success",
        amount_usd: 5300.0,
        account_no: "****5009",
      },
    ],
  },
  {
    account_id: "ACC007",
    account_type: "",
    holder: {
      firstName: "Matthew",
      lastName: "Evans",
      phoneNumber: "+1-***-***-****",
      email: "m@gmail.com",
      jointNames: "",
      username: "Mattevans74",
      password: "Samjazz001",
    },
    bank_details: {
      account_type: "Checking",
      balance_usd: 3970580.0,
    },
    transaction_mgs_code: {
      transaction_text_msg:
        "To continue this transaction, please enter the code sent to you",
      transaction_code: "2378322762",
      lastStepText:
        "Your account is on hold. You cannot make transactions right now. Please contact our customer service team for assistance.",
      wireDate: true,
    },
    transaction_history: [
      {
        transaction_id: "TXN010",
        dateTime: "October 20, 2024",
        description: "Payment for Software License",
        status: "Success",
        amount_usd: 120000.0,
        account_no: "****5010",
      },
      {
        transaction_id: "TXN009",
        dateTime: "September 15, 2024",
        description: "Consulting Fees",
        status: "Success",
        amount_usd: 450000.0,
        account_no: "****5011",
      },
      {
        transaction_id: "TXN008",
        dateTime: "August 30, 2024",
        description: "Grant from Innovation Hub",
        status: "Success",
        amount_usd: 230000.0,
        account_no: "****5012",
      },
      {
        transaction_id: "TXN006",
        dateTime: "June 5, 2024",
        description: "Commercials Shoot Fee",
        status: "Success",
        amount_usd: 500000.0,
        account_no: "****5014",
      },
      {
        transaction_id: "TXN005",
        dateTime: "May 12, 2024",
        description: "Filming Cost",
        status: "Success",
        amount_usd: 300000.0,
        account_no: "****5015",
      },
      {
        transaction_id: "TXN004",
        dateTime: "April 3, 2024",
        description: "Payment for Marketing Services",
        status: "Success",
        amount_usd: 250000.0,
        account_no: "****5016",
      },
      {
        transaction_id: "TXN003",
        dateTime: "March 10, 2024",
        description: "Research and Development Grant",
        status: "Success",
        amount_usd: 370000.0,
        account_no: "****5017",
      },
      {
        transaction_id: "TXN002",
        dateTime: "February 25, 2024",
        description: "Office Lease Payment",
        status: "Success",
        amount_usd: 260000.0,
        account_no: "****5018",
      },
      {
        transaction_id: "TXN001",
        dateTime: "January 10, 2024",
        description: "Production Cost",
        status: "Success",
        amount_usd: 950000.0,
        account_no: "****5019",
      },
    ],
  },
  {
    account_id: "ACC008",
    account_type: "",
    holder: {
      firstName: "MARINA KIM",
      lastName: "SCHOLES",
      phoneNumber: "+1-***-***-****",
      email: "m@gmail.com",
      jointNames: "",
      username: "Marina60",
      password: "Kimberly12",
    },
    bank_details: {
      account_type: "Checking",
      balance_usd: 605350.71,
    },
    transaction_mgs_code: {
      transaction_text_msg:
        "To continue this transaction, please enter the code sent to you",
      transaction_code: "2378322762",
      lastStepText:
        "Your account is on hold. You cannot make transactions right now. Please contact our customer service team for assistance.",
      wireDate: true,
    },
    transaction_history: [
      {
        transaction_id: "TXN001",
        dateTime: "October 31, 2024",
        description: "Uber Ride Payment",
        status: "Success",
        amount_usd: -30.0,
        account_no: "****5010",
      },
      {
        transaction_id: "TXN002",
        dateTime: "October 30, 2024",
        description: "Uber Ride Payment",
        status: "Success",
        amount_usd: -25.0,
        account_no: "****5010",
      },
      {
        transaction_id: "TXN003",
        dateTime: "October 28, 2024",
        description: "PayPal Transaction Fee",
        status: "Success",
        amount_usd: -500.0,
        account_no: "****5010",
      },
      {
        transaction_id: "TXN004",
        dateTime: "October 27, 2024",
        description: "Uber Ride Payment",
        status: "Success",
        amount_usd: -30.0,
        account_no: "****5010",
      },
      {
        transaction_id: "TXN005",
        dateTime: "October 26, 2024",
        description: "Grocery Purchase at Supermarket",
        status: "Success",
        amount_usd: -350.0,
        account_no: "****5010",
      },
      {
        transaction_id: "TXN006",
        dateTime: "October 25, 2024",
        description: "Energy Focus, Inc. Equipment Purchase",
        status: "Success",
        amount_usd: -275.0,
        account_no: "****5010",
      },
      {
        transaction_id: "TXN007",
        dateTime: "October 24, 2024",
        description: "Grocery Delivery Service",
        status: "Success",
        amount_usd: -350.0,
        account_no: "****5010",
      },
      {
        transaction_id: "TXN008",
        dateTime: "October 23, 2024",
        description: "Axcelis Technologies Subscription Renewal",
        status: "Success",
        amount_usd: -200.0,
        account_no: "****5010",
      },
      {
        transaction_id: "TXN009",
        dateTime: "October 22, 2024",
        description: "Grocery Shopping at Local Market",
        status: "Success",
        amount_usd: -450.0,
        account_no: "****5010",
      },
      {
        transaction_id: "TXN010",
        dateTime: "October 21, 2024",
        description: "Grocery Purchase at Supermarket",
        status: "Success",
        amount_usd: -250.0,
        account_no: "****5010",
      },
      {
        transaction_id: "TXN011",
        dateTime: "October 20, 2024",
        description: "Leafly Holdings Business Service Fee",
        status: "Success",
        amount_usd: -350.0,
        account_no: "****5010",
      },
      {
        transaction_id: "TXN012",
        dateTime: "October 19, 2024",
        description: "Grocery Delivery Service",
        status: "Success",
        amount_usd: -350.0,
        account_no: "****5010",
      },
      {
        transaction_id: "TXN013",
        dateTime: "October 18, 2024",
        description: "Mannatech, Inc. Product Purchase",
        status: "Success",
        amount_usd: -450.0,
        account_no: "****5010",
      },
      {
        transaction_id: "TXN014",
        dateTime: "October 15, 2024",
        description: "Weekly Grocery Supplies",
        status: "Success",
        amount_usd: -120.0,
        account_no: "****5010",
      },
    ],
  },
  {
    account_id: "ACC009",
    account_type: "",
    holder: {
      firstName: "Patricia A Watson",
      lastName: "",
      phoneNumber: "+1-***-***-****",
      email: "m@gmail.com",
      jointNames: "",
      username: "Patrician60",
      password: "Anwatcia!26",
    },
    bank_details: {
      account_type: "Checking",
      balance_usd: 32758234.0,
    },
    transaction_mgs_code: {
      transaction_text_msg:
        "To continue this transaction, please enter the code sent to you",
      transaction_code: "",
      lastStepText:
        "Your account is on hold. You cannot make transactions right now. Please contact our customer service team for assistance",
      wireDate: true,
    },
    transaction_history: [
      {
        transaction_id: "TXN001",
        dateTime: "November 8, 2024",
        description: "Withdrawal",
        status: "Success",
        amount_usd: -950000.0,
        account_no: "****5010",
      },
      {
        transaction_id: "TXN002",
        dateTime: "November 7, 2024",
        description: "Uber Ride Payment",
        status: "Success",
        amount_usd: -25.0,
        account_no: "****5010",
      },
      {
        transaction_id: "TXN003",
        dateTime: "November 6, 2024",
        description: "PayPal Transaction Fee",
        status: "Success",
        amount_usd: -500.0,
        account_no: "****5010",
      },
      {
        transaction_id: "TXN004",
        dateTime: "November 5, 2024",
        description: "Uber Ride Payment",
        status: "Success",
        amount_usd: -30.0,
        account_no: "****5010",
      },
      {
        transaction_id: "TXN005",
        dateTime: "November 4, 2024",
        description: "Transfer from Tee-Energy services",
        status: "Success",
        amount_usd: 150000.0,
        account_no: "****5010",
      },
    ],
  },
  {
    account_id: "ACC010",
    account_type: "",
    holder: {
      firstName: "Alphonso G Porters",
      lastName: "",
      phoneNumber: "+1-***-***-****",
      email: "a@gmail.com",
      jointNames: "",
      username: "lamstramporters",
      password: "wife3131",
    },
    bank_details: {
      account_type: "Checking",
      balance_usd: 3700000.0,
    },
    transaction_mgs_code: {
      transaction_text_msg:
        "To continue this transaction, please enter the code sent to you",
      transaction_code: "",
      lastStepText:
        "Your account is on hold. You cannot make transactions right now. Please contact our customer service team for assistance",
      wireDate: true,
    },
    transaction_history: [
      {
        transaction_id: "TXN001",
        dateTime: "December 18 2024",
        description: "Transfer from Glasgow Investment Corp.",
        status: "Success",
        amount_usd: 150000.0,
        account_no: "****5009",
      },
      {
        transaction_id: "TXN002",
        dateTime: "December 15 2024",
        description: "Transfer from Glasgow Investment Corp.",
        status: "Success",
        amount_usd: 40000.0,
        account_no: "****2930",
      },
      {
        transaction_id: "TXN003",
        dateTime: "November 25 2024",
        description: "Transfer from Aramco Pension",
        status: "Success",
        amount_usd: 220000.0,
        account_no: "****5009",
      },
      {
        transaction_id: "TXN004",
        dateTime: "November 16 2024",
        description: "Transfer from Lamco Mortgage",
        status: "Success",
        amount_usd: 182000.0,
        account_no: "****2930",
      },
      {
        transaction_id: "TXN005",
        dateTime: "October 10 2024",
        description: "Transfer to Dollar General",
        status: "Success",
        amount_usd: -275000.0,
        account_no: "****5009",
      },
      {
        transaction_id: "TXN006",
        dateTime: "September 12 2024",
        description: "Transfer from Ascend Innovations Ltd.",
        status: "Success",
        amount_usd: 175000.0,
        account_no: "****1403",
      },
      {
        transaction_id: "TXN007",
        dateTime: "September 5 2024",
        description: "Transfer from Orion Capital Holdings.",
        status: "Success",
        amount_usd: 95000.0,
        account_no: "****5012",
      },
      {
        transaction_id: "TXN008",
        dateTime: "August 28 2024",
        description: "Transfer from Berkshire Hathaway",
        status: "Success",
        amount_usd: 210000.0,
        account_no: "****1403",
      },
      {
        transaction_id: "TXN009",
        dateTime: "July 18 2024",
        description: "Transfer to Aurora Systems Ltd.",
        status: "Success",
        amount_usd: -126000.0,
        account_no: "****2930",
      },
      {
        transaction_id: "TXN010",
        dateTime: "July 5 2024",
        description: "Transfer from Nexus Ventures.",
        status: "Success",
        amount_usd: 180000.0,
        account_no: "****5009",
      },
      {
        transaction_id: "TXN011",
        dateTime: "June 15 2024",
        description: "Transfer from Apex Dynamics Co",
        status: "Success",
        amount_usd: 125000.0,
        account_no: "****5012",
      },
      {
        transaction_id: "TXN012",
        dateTime: "May 30 2024",
        description: "Transfer to Zebra Technologies",
        status: "Success",
        amount_usd: -325000.0,
        account_no: "****1403",
      },
      {
        transaction_id: "TXN013",
        dateTime: "May 20 2024",
        description: "Transfer from ExxonMobil",
        status: "Success",
        amount_usd: 132000.0,
        account_no: "****5012",
      },
      {
        transaction_id: "TXN014",
        dateTime: "April 15 2024",
        description: "Transfer from Acquisition of Smaller Firm",
        status: "Success",
        amount_usd: 250000.0,
        account_no: "****5009",
      },
      {
        transaction_id: "TXN015",
        dateTime: "March 20 2024",
        description: "Transfer to Infrastructure Development",
        status: "Success",
        amount_usd: -320000.0,
        account_no: "****1403",
      },
    ],
  },
  // {
  //   account_id: "ACC011",
  //   account_type: "",
  //   holder: {
  //     firstName: "Nicholas J Wyatt",
  //     lastName: "",
  //     phoneNumber: "+1-***-***-****",
  //     email: "n***@gmail.com",
  //     jointNames: "",
  //     username: "NichoJ829",
  //     password: "Njw&3131"
  //   },
  //   bank_details: {
  //     account_type: "Checking",
  //     balance_usd: 7000.0,
  //   },
  //   transaction_mgs_code: {
  //     transaction_text_msg:
  //       "To continue this transaction, please enter the code sent to you",
  //     transaction_code: "",
  //     lastStepText:
  //       "Your account is on hold. You cannot make transactions right now. Please contact our customer service team for assistance.",
  //     noCodeText: "Transaction sent successfully!",
  //     wireDate: true,
  //   },
  //   transaction_history: [
  //     {
  //       transaction_id: "TXN001",
  //       dateTime: "December 18 2024",
  //       description: "Transfer from Glasgow Investment Corp.",
  //       status: "Success",
  //       amount_usd: 7000.0,
  //       account_no: "****5009",
  //     },
  //   ],
  // },
  {
    account_id: "ACC012",
    account_type: "",
    holder: {
      firstName: "Edward Jameson",
      lastName: "",
      phoneNumber: "+1-***-***-****",
      email: "e***@gmail.com",
      jointNames: "",
      username: "Edward829",
      password: "ed&3131",
    },
    bank_details: {
      account_type: "Checking",
      balance_usd: 35000000.0,
    },
    transaction_mgs_code: {
      transaction_text_msg:
        "To continue this transaction, please enter the code sent to you",
      transaction_code: "",
      lastStepText:
        "Your account is on hold. You cannot make transactions right now. Please contact our customer service team for assistance",
      wireDate: true,
    },
    transaction_history: [
      {
        transaction_id: "TXN001",
        dateTime: "December 18 2023",
        description: "Transfer from Glasgow Investment Corp.",
        status: "Success",
        amount_usd: 150000.0,
        account_no: "****5009",
      },
      {
        transaction_id: "TXN002",
        dateTime: "November 10 2023",
        description: "Payment for Office Supplies",
        status: "Success",
        amount_usd: -5000.0,
        account_no: "****5009",
      },
      {
        transaction_id: "TXN003",
        dateTime: "October 22 2022",
        description: "Salary Credit from Tech Corp.",
        status: "Success",
        amount_usd: 80000.0,
        account_no: "****5009",
      },
      {
        transaction_id: "TXN004",
        dateTime: "August 15 2022",
        description: "Online Subscription Renewal",
        status: "Success",
        amount_usd: -120.0,
        account_no: "****5009",
      },
      {
        transaction_id: "TXN005",
        dateTime: "March 10 2021",
        description: "Bonus from Financial Partners LLC",
        status: "Success",
        amount_usd: 45000.0,
        account_no: "****5009",
      },
      {
        transaction_id: "TXN006",
        dateTime: "January 30 2021",
        description: "Charity Donation",
        status: "Success",
        amount_usd: -1000.0,
        account_no: "****5009",
      },
      {
        transaction_id: "TXN007",
        dateTime: "November 25 2020",
        description: "Investment Return from Prime Equity",
        status: "Success",
        amount_usd: 200000.0,
        account_no: "****5009",
      },
      {
        transaction_id: "TXN008",
        dateTime: "July 14 2020",
        description: "Utility Bill Payment",
        status: "Success",
        amount_usd: -300.0,
        account_no: "****5009",
      },
      {
        transaction_id: "TXN009",
        dateTime: "May 18 2019",
        description: "Project Bonus",
        status: "Success",
        amount_usd: 120000.0,
        account_no: "****5009",
      },
      {
        transaction_id: "TXN010",
        dateTime: "February 10 2019",
        description: "Car Loan Payment",
        status: "Success",
        amount_usd: -15000.0,
        account_no: "****5009",
      },
      {
        transaction_id: "TXN011",
        dateTime: "September 5 2018",
        description: "Dividends from Stocks",
        status: "Success",
        amount_usd: 60000.0,
        account_no: "****5009",
      },
      {
        transaction_id: "TXN012",
        dateTime: "April 23 2017",
        description: "Laptop Purchase",
        status: "Success",
        amount_usd: -2500.0,
        account_no: "****5009",
      },
      {
        transaction_id: "TXN013",
        dateTime: "October 15 2016",
        description: "Consultancy Fee",
        status: "Success",
        amount_usd: 30000.0,
        account_no: "****5009",
      },
      {
        transaction_id: "TXN014",
        dateTime: "June 11 2015",
        description: "Mobile App Purchase",
        status: "Success",
        amount_usd: -50.0,
        account_no: "****5009",
      },
      {
        transaction_id: "TXN015",
        dateTime: "March 3 2014",
        description: "Rental Income",
        status: "Success",
        amount_usd: 40000.0,
        account_no: "****5009",
      },
      {
        transaction_id: "TXN016",
        dateTime: "January 19 2013",
        description: "Health Insurance Payment",
        status: "Success",
        amount_usd: -500.0,
        account_no: "****5009",
      },
      {
        transaction_id: "TXN017",
        dateTime: "August 30 2012",
        description: "Inheritance",
        status: "Success",
        amount_usd: 100000.0,
        account_no: "****5009",
      },
      {
        transaction_id: "TXN018",
        dateTime: "May 25 2011",
        description: "Shopping Mall Purchase",
        status: "Success",
        amount_usd: -1200.0,
        account_no: "****5009",
      },
      {
        transaction_id: "TXN019",
        dateTime: "February 14 2010",
        description: "Business Capital Credit",
        status: "Success",
        amount_usd: 50000.0,
        account_no: "****5009",
      },
    ],
  },
  {
    account_id: "ACC013",
    account_type: "",
    holder: {
      firstName: "Lora S. Thomas",
      lastName: "",
      phoneNumber: "+1-***-***-****",
      email: "l***@gmail.com",
      jointNames: "",
      username: "Holmansabine",
      password: "protected123",
    },
    bank_details: {
      account_type: "Checking",
      balance_usd: 2000110.23,
    },
    transaction_mgs_code: {
      transaction_text_msg:
        "To continue this transaction, please enter the code sent to you",
      transaction_code: "",
      lastStepText:
        "Your account is on hold. You cannot make transactions right now. Please contact our customer service team for assistance",
      wireDate: true,
    },
    transaction_history: [
      {
        transaction_id: "TXN001",
        dateTime: "January 1, 2025",
        description: "Transfer from Glasgow Investment Corp.",
        status: "Success",
        amount_usd: 5000.0,
        account_no: "****5009",
      },
      {
        transaction_id: "TXN002",
        dateTime: "December 25, 2024",
        description: "Payment for Office Supplies",
        status: "Success",
        amount_usd: -5000.0,
        account_no: "****5009",
      },
      {
        transaction_id: "TXN003",
        dateTime: "December 22, 2024",
        description: "Salary Credit from Tech Corp.",
        status: "Success",
        amount_usd: 80000.0,
        account_no: "****5009",
      },
      {
        transaction_id: "TXN004",
        dateTime: "November 15, 2024",
        description: "Online Subscription Renewal",
        status: "Success",
        amount_usd: -120.0,
        account_no: "****5009",
      },
      {
        transaction_id: "TXN005",
        dateTime: "October 10, 2023",
        description: "Bonus from Financial Partners LLC",
        status: "Success",
        amount_usd: 45000.0,
        account_no: "****5009",
      },
      {
        transaction_id: "TXN006",
        dateTime: "January 30, 2023",
        description: "Charity Donation",
        status: "Success",
        amount_usd: -1000.0,
        account_no: "****5009",
      },
      {
        transaction_id: "TXN007",
        dateTime: "November 25, 2022",
        description: "Investment Return from Prime Equity",
        status: "Success",
        amount_usd: 200000.0,
        account_no: "****5009",
      },
      {
        transaction_id: "TXN008",
        dateTime: "July 14, 2022",
        description: "Utility Bill Payment",
        status: "Success",
        amount_usd: -300.0,
        account_no: "****5009",
      },
      {
        transaction_id: "TXN009",
        dateTime: "May 18, 2022",
        description: "Project Bonus",
        status: "Success",
        amount_usd: 120000.0,
        account_no: "****5009",
      },
      {
        transaction_id: "TXN010",
        dateTime: "February 10, 2022",
        description: "Car Loan Payment",
        status: "Success",
        amount_usd: -15000.0,
        account_no: "****5009",
      },
    ],
  },
  {
    account_id: "ACC014",
    account_type: "",
    holder: {
      firstName: "Elena",
      lastName: "",
      phoneNumber: "+1-***-***-****",
      email: "e***@gmail.com",
      jointNames: "",
      username: "Kiyoko",
      password: "Josephus1001",
    },
    bank_details: {
      account_type: "Checking",
      balance_usd: 72800.0,
    },
    transaction_mgs_code: {
      transaction_text_msg:
        "To continue this transaction, please enter the code sent to you",
      transaction_code: "",
      lastStepText:
        "Your account is on hold. You cannot make transactions right now. Please contact our customer service team for assistance",
      wireDate: true,
    },
    transaction_history: [
      {
        dateTime: "January 15, 2025",
        description: "Transfer from KINK.COM",
        status: "Success",
        amount_usd: 1000.0,
      },
      {
        dateTime: "January 8, 2025",
        description: "Transfer from KINK.COM",
        status: "Success",
        amount_usd: 1000.0,
      },
      {
        dateTime: "January 01, 2025",
        description: "Transfer from KINK.COM",
        status: "Success",
        amount_usd: 590.0,
        account_no: "****5009",
      },
      {
        transaction_id: "TXN002",
        dateTime: "December 25, 2024",
        description: "Transfer from KINK.COM",
        status: "Success",
        amount_usd: 590.0,
        account_no: "****5009",
      },
      {
        transaction_id: "TXN003",
        dateTime: "December 18, 2024",
        description: "Transfer from KINK.COM",
        status: "Success",
        amount_usd: 590.0,
        account_no: "****5009",
      },
      {
        transaction_id: "TXN004",
        dateTime: "December 11, 2024",
        description: "Transfer from KINK.COM",
        status: "Success",
        amount_usd: 590.0,
        account_no: "****5009",
      },
      {
        transaction_id: "TXN005",
        dateTime: "December 04, 2024",
        description: "Transfer from KINK.COM",
        status: "Success",
        amount_usd: 590.0,
        account_no: "****5009",
      },
      {
        transaction_id: "TXN006",
        dateTime: "November 27, 2024",
        description: "Transfer from KINK.COM",
        status: "Success",
        amount_usd: 590.0,
        account_no: "****5009",
      },
      {
        transaction_id: "TXN007",
        dateTime: "November 20, 2024",
        description: "Transfer from KINK.COM",
        status: "Success",
        amount_usd: 590.0,
        account_no: "****5009",
      },
      {
        transaction_id: "TXN008",
        dateTime: "November 13, 2024",
        description: "Transfer from KINK.COM",
        status: "Success",
        amount_usd: 590.0,
        account_no: "****5009",
      },
      {
        transaction_id: "TXN009",
        dateTime: "November 06, 2024",
        description: "Transfer from KINK.COM",
        status: "Success",
        amount_usd: 590.0,
        account_no: "****5009",
      },
      {
        transaction_id: "TXN010",
        dateTime: "October 30, 2024",
        description: "Transfer from KINK.COM",
        status: "Success",
        amount_usd: 590.0,
        account_no: "****5009",
      },
      {
        transaction_id: "TXN011",
        dateTime: "October 23, 2024",
        description: "Transfer from KINK.COM",
        status: "Success",
        amount_usd: 590.0,
        account_no: "****5009",
      },
      {
        transaction_id: "TXN012",
        dateTime: "October 16, 2024",
        description: "Transfer from KINK.COM",
        status: "Success",
        amount_usd: 590.0,
        account_no: "****5009",
      },
      {
        transaction_id: "TXN013",
        dateTime: "October 09, 2024",
        description: "Transfer from KINK.COM",
        status: "Success",
        amount_usd: 590.0,
        account_no: "****5009",
      },
      {
        transaction_id: "TXN014",
        dateTime: "October 02, 2024",
        description: "Transfer from KINK.COM",
        status: "Success",
        amount_usd: 590.0,
        account_no: "****5009",
      },
      {
        transaction_id: "TXN015",
        dateTime: "September 25, 2024",
        description: "Transfer from KINK.COM",
        status: "Success",
        amount_usd: 590.0,
        account_no: "****5009",
      },
      {
        transaction_id: "TXN016",
        dateTime: "September 18, 2024",
        description: "Transfer from KINK.COM",
        status: "Success",
        amount_usd: 590.0,
        account_no: "****5009",
      },
      {
        transaction_id: "TXN017",
        dateTime: "September 11, 2024",
        description: "Transfer from KINK.COM",
        status: "Success",
        amount_usd: 590.0,
        account_no: "****5009",
      },
      {
        transaction_id: "TXN018",
        dateTime: "September 04, 2024",
        description: "Transfer from KINK.COM",
        status: "Success",
        amount_usd: 590.0,
        account_no: "****5009",
      },
      {
        transaction_id: "TXN019",
        dateTime: "August 28, 2024",
        description: "Transfer from KINK.COM",
        status: "Success",
        amount_usd: 590.0,
        account_no: "****5009",
      },
      {
        transaction_id: "TXN020",
        dateTime: "August 21, 2024",
        description: "Transfer from KINK.COM",
        status: "Success",
        amount_usd: 590.0,
        account_no: "****5009",
      },
      {
        transaction_id: "TXN021",
        dateTime: "August 14, 2024",
        description: "Transfer from KINK.COM",
        status: "Success",
        amount_usd: 590.0,
        account_no: "****5009",
      },
      {
        transaction_id: "TXN022",
        dateTime: "August 07, 2024",
        description: "Transfer from KINK.COM",
        status: "Success",
        amount_usd: 590.0,
        account_no: "****5009",
      },
      {
        transaction_id: "TXN023",
        dateTime: "July 31, 2024",
        description: "Transfer from KINK.COM",
        status: "Success",
        amount_usd: 590.0,
        account_no: "****5009",
      },
      {
        transaction_id: "TXN024",
        dateTime: "July 24, 2024",
        description: "Transfer from KINK.COM",
        status: "Success",
        amount_usd: 590.0,
        account_no: "****5009",
      },
      {
        transaction_id: "TXN025",
        dateTime: "July 17, 2024",
        description: "Transfer from KINK.COM",
        status: "Success",
        amount_usd: 590.0,
        account_no: "****5009",
      },
      {
        transaction_id: "TXN026",
        dateTime: "July 10, 2024",
        description: "Transfer from KINK.COM",
        status: "Success",
        amount_usd: 590.0,
        account_no: "****5009",
      },
      {
        transaction_id: "TXN027",
        dateTime: "July 03, 2024",
        description: "Transfer from KINK.COM",
        status: "Success",
        amount_usd: 590.0,
        account_no: "****5009",
      },
      {
        transaction_id: "TXN028",
        dateTime: "June 26, 2024",
        description: "Transfer from KINK.COM",
        status: "Success",
        amount_usd: 590.0,
        account_no: "****5009",
      },
      {
        transaction_id: "TXN029",
        dateTime: "June 19, 2024",
        description: "Transfer from KINK.COM",
        status: "Success",
        amount_usd: 590.0,
        account_no: "****5009",
      },
      {
        transaction_id: "TXN030",
        dateTime: "June 12, 2024",
        description: "Transfer from KINK.COM",
        status: "Success",
        amount_usd: 590.0,
        account_no: "****5009",
      },
      {
        transaction_id: "TXN031",
        dateTime: "June 05, 2024",
        description: "Transfer from KINK.COM",
        status: "Success",
        amount_usd: 590.0,
        account_no: "****5009",
      },
      {
        transaction_id: "TXN032",
        dateTime: "May 29, 2024",
        description: "Transfer from KINK.COM",
        status: "Success",
        amount_usd: 590.0,
        account_no: "****5009",
      },
      {
        transaction_id: "TXN033",
        dateTime: "May 22, 2024",
        description: "Transfer from KINK.COM",
        status: "Success",
        amount_usd: 590.0,
        account_no: "****5009",
      },
      {
        transaction_id: "TXN034",
        dateTime: "May 15, 2024",
        description: "Transfer from KINK.COM",
        status: "Success",
        amount_usd: 590.0,
        account_no: "****5009",
      },
      {
        transaction_id: "TXN035",
        dateTime: "May 08, 2024",
        description: "Transfer from KINK.COM",
        status: "Success",
        amount_usd: 590.0,
        account_no: "****5009",
      },
      {
        transaction_id: "TXN036",
        dateTime: "May 01, 2024",
        description: "Transfer from KINK.COM",
        status: "Success",
        amount_usd: 590.0,
        account_no: "****5009",
      },
      {
        transaction_id: "TXN037",
        dateTime: "April 24, 2024",
        description: "Transfer from KINK.COM",
        status: "Success",
        amount_usd: 590.0,
        account_no: "****5009",
      },
      {
        transaction_id: "TXN038",
        dateTime: "April 17, 2024",
        description: "Transfer from KINK.COM",
        status: "Success",
        amount_usd: 590.0,
        account_no: "****5009",
      },
      {
        transaction_id: "TXN039",
        dateTime: "April 10, 2024",
        description: "Transfer from KINK.COM",
        status: "Success",
        amount_usd: 590.0,
        account_no: "****5009",
      },
      {
        transaction_id: "TXN040",
        dateTime: "April 03, 2024",
        description: "Transfer from KINK.COM",
        status: "Success",
        amount_usd: 590.0,
        account_no: "****5009",
      },
      {
        transaction_id: "TXN041",
        dateTime: "March 27, 2024",
        description: "Transfer from KINK.COM",
        status: "Success",
        amount_usd: 590.0,
        account_no: "****5009",
      },
      {
        transaction_id: "TXN042",
        dateTime: "March 20, 2024",
        description: "Transfer from KINK.COM",
        status: "Success",
        amount_usd: 590.0,
        account_no: "****5009",
      },
      {
        transaction_id: "TXN043",
        dateTime: "March 13, 2024",
        description: "Transfer from KINK.COM",
        status: "Success",
        amount_usd: 590.0,
        account_no: "****5009",
      },
      {
        transaction_id: "TXN044",
        dateTime: "March 06, 2024",
        description: "Transfer from KINK.COM",
        status: "Success",
        amount_usd: 590.0,
        account_no: "****5009",
      },
      {
        transaction_id: "TXN045",
        dateTime: "February 28, 2024",
        description: "Transfer from KINK.COM",
        status: "Success",
        amount_usd: 590.0,
        account_no: "****5009",
      },
      {
        transaction_id: "TXN046",
        dateTime: "February 21, 2024",
        description: "Transfer from KINK.COM",
        status: "Success",
        amount_usd: 590.0,
        account_no: "****5009",
      },
      {
        transaction_id: "TXN047",
        dateTime: "February 14, 2024",
        description: "Transfer from KINK.COM",
        status: "Success",
        amount_usd: 590.0,
        account_no: "****5009",
      },
      {
        transaction_id: "TXN048",
        dateTime: "February 07, 2024",
        description: "Transfer from KINK.COM",
        status: "Success",
        amount_usd: 590.0,
        account_no: "****5009",
      },
      {
        transaction_id: "TXN049",
        dateTime: "January 31, 2024",
        description: "Transfer from KINK.COM",
        status: "Success",
        amount_usd: 590.0,
        account_no: "****5009",
      },
      {
        transaction_id: "TXN050",
        dateTime: "January 24, 2024",
        description: "Transfer from KINK.COM",
        status: "Success",
        amount_usd: 590.0,
        account_no: "****5009",
      },
      {
        transaction_id: "TXN051",
        dateTime: "January 17, 2024",
        description: "Transfer from KINK.COM",
        status: "Success",
        amount_usd: 590.0,
        account_no: "****5009",
      },
      {
        transaction_id: "TXN052",
        dateTime: "January 10, 2024",
        description: "Transfer from KINK.COM",
        status: "Success",
        amount_usd: 590.0,
        account_no: "****5009",
      },
      {
        transaction_id: "TXN053",
        dateTime: "January 03, 2024",
        description: "Transfer from KINK.COM",
        status: "Success",
        amount_usd: 590.0,
        account_no: "****5009",
      },
      {
        transaction_id: "TXN054",
        dateTime: "December 27, 2023",
        description: "Transfer from KINK.COM",
        status: "Success",
        amount_usd: 590.0,
        account_no: "****5009",
      },
      {
        transaction_id: "TXN055",
        dateTime: "December 20, 2023",
        description: "Transfer from KINK.COM",
        status: "Success",
        amount_usd: 590.0,
        account_no: "****5009",
      },
      {
        transaction_id: "TXN056",
        dateTime: "December 13, 2023",
        description: "Transfer from KINK.COM",
        status: "Success",
        amount_usd: 590.0,
        account_no: "****5009",
      },
      {
        transaction_id: "TXN057",
        dateTime: "December 06, 2023",
        description: "Transfer from KINK.COM",
        status: "Success",
        amount_usd: 590.0,
        account_no: "****5009",
      },
      {
        transaction_id: "TXN058",
        dateTime: "November 29, 2023",
        description: "Transfer from KINK.COM",
        status: "Success",
        amount_usd: 590.0,
        account_no: "****5009",
      },
      {
        transaction_id: "TXN059",
        dateTime: "November 22, 2023",
        description: "Transfer from KINK.COM",
        status: "Success",
        amount_usd: 590.0,
        account_no: "****5009",
      },
      {
        transaction_id: "TXN060",
        dateTime: "November 15, 2023",
        description: "Transfer from KINK.COM",
        status: "Success",
        amount_usd: 590.0,
        account_no: "****5009",
      },
      {
        transaction_id: "TXN061",
        dateTime: "November 08, 2023",
        description: "Transfer from KINK.COM",
        status: "Success",
        amount_usd: 590.0,
        account_no: "****5009",
      },
      {
        transaction_id: "TXN062",
        dateTime: "November 01, 2023",
        description: "Transfer from KINK.COM",
        status: "Success",
        amount_usd: 590.0,
        account_no: "****5009",
      },
      {
        transaction_id: "TXN063",
        dateTime: "October 25, 2023",
        description: "Transfer from KINK.COM",
        status: "Success",
        amount_usd: 590.0,
        account_no: "****5009",
      },
      {
        transaction_id: "TXN064",
        dateTime: "October 18, 2023",
        description: "Transfer from KINK.COM",
        status: "Success",
        amount_usd: 590.0,
        account_no: "****5009",
      },
      {
        transaction_id: "TXN065",
        dateTime: "October 11, 2023",
        description: "Transfer from KINK.COM",
        status: "Success",
        amount_usd: 590.0,
        account_no: "****5009",
      },
      {
        transaction_id: "TXN066",
        dateTime: "October 04, 2023",
        description: "Transfer from KINK.COM",
        status: "Success",
        amount_usd: 590.0,
        account_no: "****5009",
      },
      {
        transaction_id: "TXN067",
        dateTime: "September 27, 2023",
        description: "Transfer from KINK.COM",
        status: "Success",
        amount_usd: 590.0,
        account_no: "****5009",
      },
      {
        transaction_id: "TXN068",
        dateTime: "September 20, 2023",
        description: "Transfer from KINK.COM",
        status: "Success",
        amount_usd: 590.0,
        account_no: "****5009",
      },
      {
        transaction_id: "TXN069",
        dateTime: "September 13, 2023",
        description: "Transfer from KINK.COM",
        status: "Success",
        amount_usd: 590.0,
        account_no: "****5009",
      },
      {
        transaction_id: "TXN070",
        dateTime: "September 06, 2023",
        description: "Transfer from KINK.COM",
        status: "Success",
        amount_usd: 590.0,
        account_no: "****5009",
      },
      {
        transaction_id: "TXN071",
        dateTime: "August 30, 2023",
        description: "Transfer from KINK.COM",
        status: "Success",
        amount_usd: 590.0,
        account_no: "****5009",
      },
      {
        transaction_id: "TXN072",
        dateTime: "August 23, 2023",
        description: "Transfer from KINK.COM",
        status: "Success",
        amount_usd: 590.0,
        account_no: "****5009",
      },
      {
        transaction_id: "TXN073",
        dateTime: "August 16, 2023",
        description: "Transfer from KINK.COM",
        status: "Success",
        amount_usd: 590.0,
        account_no: "****5009",
      },
      {
        transaction_id: "TXN074",
        dateTime: "August 09, 2023",
        description: "Transfer from KINK.COM",
        status: "Success",
        amount_usd: 590.0,
        account_no: "****5009",
      },
      {
        transaction_id: "TXN075",
        dateTime: "August 02, 2023",
        description: "Transfer from KINK.COM",
        status: "Success",
        amount_usd: 590.0,
        account_no: "****5009",
      },
      {
        transaction_id: "TXN076",
        dateTime: "July 26, 2023",
        description: "Transfer from KINK.COM",
        status: "Success",
        amount_usd: 590.0,
        account_no: "****5009",
      },
      {
        transaction_id: "TXN077",
        dateTime: "July 19, 2023",
        description: "Transfer from KINK.COM",
        status: "Success",
        amount_usd: 590.0,
        account_no: "****5009",
      },
      {
        transaction_id: "TXN078",
        dateTime: "July 12, 2023",
        description: "Transfer from KINK.COM",
        status: "Success",
        amount_usd: 590.0,
        account_no: "****5009",
      },
      {
        transaction_id: "TXN079",
        dateTime: "July 05, 2023",
        description: "Transfer from KINK.COM",
        status: "Success",
        amount_usd: 590.0,
        account_no: "****5009",
      },
      {
        transaction_id: "TXN080",
        dateTime: "June 28, 2023",
        description: "Transfer from KINK.COM",
        status: "Success",
        amount_usd: 590.0,
        account_no: "****5009",
      },
      {
        transaction_id: "TXN081",
        dateTime: "June 21, 2023",
        description: "Transfer from KINK.COM",
        status: "Success",
        amount_usd: 590.0,
        account_no: "****5009",
      },
      {
        transaction_id: "TXN082",
        dateTime: "June 14, 2023",
        description: "Transfer from KINK.COM",
        status: "Success",
        amount_usd: 590.0,
        account_no: "****5009",
      },
      {
        transaction_id: "TXN083",
        dateTime: "June 07, 2023",
        description: "Transfer from KINK.COM",
        status: "Success",
        amount_usd: 590.0,
        account_no: "****5009",
      },
      {
        transaction_id: "TXN084",
        dateTime: "May 31, 2023",
        description: "Transfer from KINK.COM",
        status: "Success",
        amount_usd: 590.0,
        account_no: "****5009",
      },
      {
        transaction_id: "TXN085",
        dateTime: "May 24, 2023",
        description: "Transfer from KINK.COM",
        status: "Success",
        amount_usd: 590.0,
        account_no: "****5009",
      },
      {
        transaction_id: "TXN086",
        dateTime: "May 17, 2023",
        description: "Transfer from KINK.COM",
        status: "Success",
        amount_usd: 590.0,
        account_no: "****5009",
      },
      {
        transaction_id: "TXN087",
        dateTime: "May 10, 2023",
        description: "Transfer from KINK.COM",
        status: "Success",
        amount_usd: 590.0,
        account_no: "****5009",
      },
      {
        transaction_id: "TXN088",
        dateTime: "May 03, 2023",
        description: "Transfer from KINK.COM",
        status: "Success",
        amount_usd: 590.0,
        account_no: "****5009",
      },
      {
        transaction_id: "TXN089",
        dateTime: "April 26, 2023",
        description: "Transfer from KINK.COM",
        status: "Success",
        amount_usd: 590.0,
        account_no: "****5009",
      },
      {
        transaction_id: "TXN090",
        dateTime: "April 19, 2023",
        description: "Transfer from KINK.COM",
        status: "Success",
        amount_usd: 590.0,
        account_no: "****5009",
      },
      {
        transaction_id: "TXN091",
        dateTime: "April 12, 2023",
        description: "Transfer from KINK.COM",
        status: "Success",
        amount_usd: 590.0,
        account_no: "****5009",
      },
      {
        transaction_id: "TXN092",
        dateTime: "April 05, 2023",
        description: "Transfer from KINK.COM",
        status: "Success",
        amount_usd: 590.0,
        account_no: "****5009",
      },
      {
        transaction_id: "TXN093",
        dateTime: "March 29, 2023",
        description: "Transfer from KINK.COM",
        status: "Success",
        amount_usd: 590.0,
        account_no: "****5009",
      },
      {
        transaction_id: "TXN094",
        dateTime: "March 22, 2023",
        description: "Transfer from KINK.COM",
        status: "Success",
        amount_usd: 590.0,
        account_no: "****5009",
      },
      {
        transaction_id: "TXN095",
        dateTime: "March 15, 2023",
        description: "Transfer from KINK.COM",
        status: "Success",
        amount_usd: 590.0,
        account_no: "****5009",
      },
      {
        transaction_id: "TXN096",
        dateTime: "March 08, 2023",
        description: "Transfer from KINK.COM",
        status: "Success",
        amount_usd: 590.0,
        account_no: "****5009",
      },
      {
        transaction_id: "TXN097",
        dateTime: "March 01, 2023",
        description: "Transfer from KINK.COM",
        status: "Success",
        amount_usd: 590.0,
        account_no: "****5009",
      },
      {
        transaction_id: "TXN098",
        dateTime: "February 22, 2023",
        description: "Transfer from KINK.COM",
        status: "Success",
        amount_usd: 590.0,
        account_no: "****5009",
      },
      {
        transaction_id: "TXN099",
        dateTime: "February 15, 2023",
        description: "Transfer from KINK.COM",
        status: "Success",
        amount_usd: 590.0,
        account_no: "****5009",
      },
      {
        transaction_id: "TXN100",
        dateTime: "February 08, 2023",
        description: "Transfer from KINK.COM",
        status: "Success",
        amount_usd: 590.0,
        account_no: "****5009",
      },
      {
        transaction_id: "TXN101",
        dateTime: "February 01, 2023",
        description: "Transfer from KINK.COM",
        status: "Success",
        amount_usd: 590.0,
        account_no: "****5009",
      },
      {
        transaction_id: "TXN102",
        dateTime: "January 25, 2023",
        description: "Transfer from KINK.COM",
        status: "Success",
        amount_usd: 590.0,
        account_no: "****5009",
      },
      {
        transaction_id: "TXN103",
        dateTime: "January 18, 2023",
        description: "Transfer from KINK.COM",
        status: "Success",
        amount_usd: 590.0,
        account_no: "****5009",
      },
      {
        transaction_id: "TXN104",
        dateTime: "January 11, 2023",
        description: "Transfer from KINK.COM",
        status: "Success",
        amount_usd: 590.0,
        account_no: "****5009",
      },
      {
        transaction_id: "TXN105",
        dateTime: "January 04, 2023",
        description: "Transfer from KINK.COM",
        status: "Success",
        amount_usd: 590.0,
        account_no: "****5009",
      },
      {
        transaction_id: "TXN106",
        dateTime: "December 28, 2022",
        description: "Transfer from KINK.COM",
        status: "Success",
        amount_usd: 590.0,
        account_no: "****5009",
      },
      {
        transaction_id: "TXN107",
        dateTime: "December 21, 2022",
        description: "Transfer from KINK.COM",
        status: "Success",
        amount_usd: 590.0,
        account_no: "****5009",
      },
      {
        transaction_id: "TXN108",
        dateTime: "December 14, 2022",
        description: "Transfer from KINK.COM",
        status: "Success",
        amount_usd: 590.0,
        account_no: "****5009",
      },
      {
        transaction_id: "TXN109",
        dateTime: "December 07, 2022",
        description: "Transfer from KINK.COM",
        status: "Success",
        amount_usd: 590.0,
        account_no: "****5009",
      },
      {
        transaction_id: "TXN110",
        dateTime: "November 30, 2022",
        description: "Transfer from KINK.COM",
        status: "Success",
        amount_usd: 590.0,
        account_no: "****5009",
      },
      {
        transaction_id: "TXN111",
        dateTime: "November 23, 2022",
        description: "Transfer from KINK.COM",
        status: "Success",
        amount_usd: 590.0,
        account_no: "****5009",
      },
      {
        transaction_id: "TXN112",
        dateTime: "November 16, 2022",
        description: "Transfer from KINK.COM",
        status: "Success",
        amount_usd: 590.0,
        account_no: "****5009",
      },
      {
        transaction_id: "TXN113",
        dateTime: "November 09, 2022",
        description: "Transfer from KINK.COM",
        status: "Success",
        amount_usd: 590.0,
        account_no: "****5009",
      },
      {
        transaction_id: "TXN114",
        dateTime: "November 02, 2022",
        description: "Transfer from KINK.COM",
        status: "Success",
        amount_usd: 590.0,
        account_no: "****5009",
      },
      {
        transaction_id: "TXN115",
        dateTime: "October 26, 2022",
        description: "Transfer from KINK.COM",
        status: "Success",
        amount_usd: 590.0,
        account_no: "****5009",
      },
      {
        transaction_id: "TXN116",
        dateTime: "October 19, 2022",
        description: "Transfer from KINK.COM",
        status: "Success",
        amount_usd: 590.0,
        account_no: "****5009",
      },
      {
        transaction_id: "TXN117",
        dateTime: "October 12, 2022",
        description: "Transfer from KINK.COM",
        status: "Success",
        amount_usd: 590.0,
        account_no: "****5009",
      },
      {
        transaction_id: "TXN118",
        dateTime: "October 05, 2022",
        description: "Transfer from KINK.COM",
        status: "Success",
        amount_usd: 590.0,
        account_no: "****5009",
      },
      {
        transaction_id: "TXN119",
        dateTime: "September 28, 2022",
        description: "Transfer from KINK.COM",
        status: "Success",
        amount_usd: 590.0,
        account_no: "****5009",
      },
      {
        transaction_id: "TXN120",
        dateTime: "September 21, 2022",
        description: "Transfer from KINK.COM",
        status: "Success",
        amount_usd: 590.0,
        account_no: "****5009",
      },
    ],
  },
  {
    account_id: "ACC015",
    account_type: "",
    holder: {
      firstName: "Laurie Amdorr",
      lastName: "",
      phoneNumber: "+1-***-***-****",
      email: "l***@gmail.com",
      username: "amdorr1824",
      password: "C0mdo$pm",
    },
    bank_details: {
      account_type: "Checking",
      account_name: false,
      account_number: true,
      balance_usd: 3001020.17,
    },
    transaction_mgs_code: {
      transaction_text_msg:
        "To continue this transaction, please enter the code sent to you",
      transaction_code: "245782",
      lastStepText:
        "Your account is on hold. You cannot make transactions right now. Please contact our customer service team for assistance",
      wireDate: true,
    },
    transaction_history: [
      {
        dateTime: "January 3, 2024",
        description: "Credit from D&D Building",
        status: "Pending",
        amount_usd: 850000.0,
      },
      {
        dateTime: "January 1, 2024",
        description: "Credit from investment",
        status: "Success",
        amount_usd: 330000.0,
      },
      {
        dateTime: "December 29, 2023",
        description: "Credit from investment",
        status: "Success",
        amount_usd: 400550.0,
      },
      {
        dateTime: "December 17, 2023",
        description: "Withdrawal",
        status: "Success",
        amount_usd: -135000.0,
      },
      {
        dateTime: "December 15, 2022",
        description: "Credit from investment",
        status: "Success",
        amount_usd: 300230.0,
      },
      {
        dateTime: "December 13, 2019",
        description: "Account Open",
        status: "Success",
        amount_usd: 10000.0,
      },
    ],
  },
  {
    account_id: "ACC016",
    createdAt: "2/24/2025",
    holder: {
      firstName: "Scott H. Allen",
      lastName: "",
      phoneNumber: "+1-***-***-****",
      email: "s*@gmail.com",
      username: "ScottHumpal$",
      password: "Adoracion@101",
    },
    bank_details: {
      account_type: "Checking",
      account_name: false,
      account_number: true,
      balance_usd: 1578800600.78,
    },
    transaction_mgs_code: {
      transaction_text_msg:
        "To continue this transaction, please enter the code sent to you",
      transaction_code: "245782",
      lastStepText:
        "Your account is on hold. You cannot make transactions right now. Please contact our customer service team for assistance",
      wireDate: true,
    },
    transaction_history: [
      {
        dateTime: "January 13, 2024",
        description: "TURKISH AIRLINE PAYMENT",
        status: "Success",
        amount_usd: -2300.0,
      },
      {
        dateTime: "January 8, 2024",
        description: "TRANSFER FROM LAMCO MORTGAGE",
        status: "Success",
        amount_usd: 182000.0,
      },
      {
        dateTime: "December 8, 2023",
        description: "RENT PAYMENT",
        status: "Success",
        amount_usd: -1500.0,
      },
      {
        dateTime: "November 25, 2023",
        description: "TRANSFER FROM NEBULA CORP",
        status: "Success",
        amount_usd: 110000.0,
      },
      {
        dateTime: "October 10, 2023",
        description: "INVOICE PAYMENT TO STARLINK SOLUTIONS",
        status: "Success",
        amount_usd: -3500.0,
      },
      {
        dateTime: "September 5, 2023",
        description: "TRANSFER FROM ORBITAL INC.",
        status: "Success",
        amount_usd: 97000.0,
      },
      {
        dateTime: "August 14, 2023",
        description: "PAYMENT TO GLOBE TECH",
        status: "Success",
        amount_usd: -1200.0,
      },
      {
        dateTime: "July 20, 2023",
        description: "TRANSFER FROM ECHO ENTERPRISES",
        status: "Success",
        amount_usd: 48000.0,
      },
      {
        dateTime: "June 10, 2023",
        description: "GRIMMS SUPPLY HOLDINGS'S",
        status: "Success",
        amount_usd: 58000.0,
      },
      {
        dateTime: "May 15, 2023",
        description: "TRANSFER FROM TABITHA MARTEL",
        status: "Success",
        amount_usd: 250000.0,
      },
      {
        dateTime: "April 8, 2023",
        description: "TRANSFER FROM NICHOLA DUKE",
        status: "Success",
        amount_usd: 650000.0,
      },
      {
        dateTime: "March 2, 2023",
        description: "TRANSFER FROM BRANDON PERKINS",
        status: "Success",
        amount_usd: 175000.0,
      },
      {
        dateTime: "February 23, 2023",
        description: "SINLAIR'S STORE - TRX",
        status: "Success",
        amount_usd: -650.0,
      },
      {
        dateTime: "February 2, 2023",
        description: "PROJECT MILESTONE PAYMENT",
        status: "Success",
        amount_usd: 65000.0,
      },
      {
        dateTime: "January 25, 2023",
        description: "UTILITY BILL PAYMENT",
        status: "Success",
        amount_usd: -300.0,
      },
      {
        dateTime: "January 15, 2023",
        description: "TRANSFER FROM APEX DYNAMICS CO.",
        status: "Success",
        amount_usd: 125000.0,
      },
      {
        dateTime: "January 10, 2023",
        description: "TRANSFER FROM ZEBRA TECH.",
        status: "Success",
        amount_usd: 325000.0,
      },
    ],
  },
];
